# Generated by Django 5.1.6 on 2025-04-02 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussines_name', models.CharField(max_length=100)),
                ('bussines_category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('uniq', models.CharField(editable=False, max_length=20, unique=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user')),
            ],
        ),
    ]
