# Generated by Django 5.1.6 on 2025-03-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(max_length=10),
        ),
    ]
