# Generated by Django 5.1.6 on 2025-04-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0002_uploadedfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user'),
        ),
    ]
