# Generated by Django 5.1.6 on 2025-03-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0003_alter_login_email_alter_user_gender_bussines'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
