# Generated by Django 5.1.6 on 2025-04-05 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0003_alter_uploadedfile_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('name_card', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
    ]
