# Generated by Django 5.1.6 on 2025-04-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0005_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
    ]
