# Generated by Django 5.1.6 on 2025-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0006_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
