# Generated by Django 5.1.6 on 2025-04-05 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0006_remove_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='dateee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='merchant_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='payment_method',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='transaction_type',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
