# Generated by Django 5.1.6 on 2025-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0007_alter_survey_option3_alter_survey_option4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
