# Generated by Django 5.1.6 on 2025-03-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0008_alter_survey_option3_alter_survey_option4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user')),
            ],
        ),
    ]
