# Generated by Django 5.1.6 on 2025-04-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0009_alter_productreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('reason_to_leave_previous_company', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
