# Generated by Django 5.1.6 on 2025-04-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0010_employeedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user'),
            preserve_default=False,
        ),
    ]
