# Generated by Django 5.1.6 on 2025-04-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0012_employeedetails_company_name_employeedetails_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Other', 'Other')], max_length=10)),
                ('degree_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('grade_or_percentage', models.CharField(max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user')),
            ],
        ),
    ]
