# Generated by Django 5.1.6 on 2025-04-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0013_educationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
