# Generated by Django 5.1.6 on 2025-04-09 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0014_data_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='buss_data_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(max_length=100)),
                ('no_of_row', models.IntegerField()),
                ('cancel_status', models.IntegerField(default=0)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines')),
            ],
        ),
    ]
