# Generated by Django 5.1.6 on 2025-04-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0017_buss_data_request_accept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
    ]
