# Generated by Django 5.1.6 on 2025-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0018_alter_payment_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='buss_data_request',
            name='Payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
