# Generated by Django 5.1.6 on 2025-04-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0019_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buss_data_request',
            old_name='Payment_status',
            new_name='payment_status',
        ),
    ]
