# Generated by Django 5.1.6 on 2025-04-13 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0020_rename_payment_status_buss_data_request_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_tranfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('req_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.buss_data_request')),
            ],
        ),
    ]
