# Generated by Django 5.1.6 on 2025-04-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0021_data_tranfer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_tranfer',
            new_name='data_transfer',
        ),
    ]
