# Generated by Django 5.1.6 on 2025-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0022_rename_data_tranfer_data_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss_data_request',
            name='transfer_status',
            field=models.IntegerField(default=0),
        ),
    ]
