# Generated by Django 5.1.6 on 2025-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0023_buss_data_request_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
