# Generated by Django 5.1.6 on 2025-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0024_educationdetail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetail',
            name='file',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_files/'),
        ),
    ]
