# Generated by Django 5.1.6 on 2025-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0027_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
