# Generated by Django 5.1.6 on 2025-04-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0028_alter_user_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('about_product', models.TextField()),
                ('suggesions', models.TextField()),
                ('liked_features', models.TextField(blank=True, null=True)),
                ('disliked_features', models.TextField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user')),
            ],
        ),
    ]
