# Generated by Django 5.1.6 on 2025-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0031_user_city_user_country_user_dob_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserhistory',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productopinion',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
    ]
