# Generated by Django 5.1.6 on 2025-04-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0032_browserhistory_buy_status_educationdetail_buy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AlterField(
            model_name='productopinion',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buy_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
    ]
