# Generated by Django 5.1.6 on 2025-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0033_alter_educationdetail_buy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productopinion',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='buy_status',
            field=models.IntegerField(default=0),
        ),
    ]
