# Generated by Django 5.1.6 on 2025-04-17 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0034_alter_educationdetail_buy_status_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_transfer',
            old_name='req_login',
            new_name='data_request',
        ),
        migrations.RemoveField(
            model_name='browserhistory',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='data_transfer',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='productopinion',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='buy_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='buy_status',
        ),
        migrations.AddField(
            model_name='data_transfer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dataapp.bussines'),
        ),
        migrations.AddField(
            model_name='data_transfer',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='data_transfer',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data_transfer',
            name='viewed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
