# Generated by Django 5.1.6 on 2025-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0035_rename_req_login_data_transfer_data_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('ifsc_code', models.CharField(max_length=11, unique=True)),
                ('cussomer_name', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
                ('total_balance', models.IntegerField()),
            ],
        ),
    ]
