# Generated by Django 5.1.6 on 2025-04-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0036_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='cussomer_name',
            new_name='customer_name',
        ),
    ]
