# Generated by Django 5.1.6 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0037_rename_cussomer_name_bank_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='total_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
