# Generated by Django 5.1.6 on 2025-04-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0038_alter_bank_expiry_date_alter_bank_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.login')),
            ],
        ),
    ]
