# Generated by Django 5.1.6 on 2025-04-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0039_alter_bank_expiry_date_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user'),
        ),
    ]
