# Generated by Django 5.1.6 on 2025-04-18 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0040_remove_wallet_total_amount_wallet_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='total_earnings',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user'),
        ),
    ]
