# Generated by Django 5.1.6 on 2025-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0043_alter_userwallet_balance_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss_data_request',
            name='table_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buss_data_request',
            name='table_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
