# Generated by Django 5.1.6 on 2025-04-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0044_buss_data_request_table_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buss_data_request',
            name='transfer_status',
        ),
    ]
