# Generated by Django 5.1.6 on 2025-04-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0046_chatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Dataapp.login'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='Dataapp.login'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
