# Generated by Django 5.1.6 on 2025-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0047_alter_chatmodel_receiver_alter_chatmodel_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='sender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
