# Generated by Django 5.1.6 on 2025-04-23 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataapp', '0048_alter_chatmodel_receiver_alter_chatmodel_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ai_extract/')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dateee', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(default='0', max_length=100)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('payment_method', models.CharField(default='0', max_length=100)),
                ('merchant_name', models.CharField(default='0', max_length=100)),
                ('category', models.CharField(default='0', max_length=100)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataapp.user')),
            ],
        ),
    ]
